name: Add Pull Request Labels and Assign to Project
on:
  pull_request_target:
    types: [opened]
  workflow_dispatch:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: ericcornelissen/labeler@label-based-on-status
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  assign-to-project:
    runs-on: ubuntu-latest
    name: Assign to Project
    needs: triage
    env:
      MY_GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGN_WORKFLOW_TOKEN }}
    steps:
    - id: get-labels
      name: Get labels
      run: |
        pull_number="$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
        labels="$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/simple-icons/simple-icons/pulls/$pull_number | jq '.labels[].name' | tr '\n' ',' | sed 's/"//g' | sed 's/,$//')"
        echo "::set-output name=labels::$labels"
    - name: Assign pull requests to "Unprioritised"
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: contains(steps.get-labels.outputs.labels, 'icon outdated') == false
      with:
        project: https://github.com/orgs/simple-icons/projects/2
        column_name: Unprioritised

    - name: Assign `icon outdated` pull requests to "Priority 1"
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: contains(steps.get-labels.outputs.labels, 'icon outdated')
      with:
        project: https://github.com/orgs/simple-icons/projects/2
        column_name: Priority 1
