name: Create Release Pull Request
on:
  workflow_dispatch:
  schedule:
    # "At 00:00 on Sunday" (https://crontab.guru/once-a-week)
    - cron: "0 0 * * 0"

# This Workflow can be triggered manually through the GitHub UI or API. For the
# API use the following request:
#   curl -X POST \
#        -H "Authorization: Bearer <token>" \
#        -d '{"ref":"develop"}' \
#        https://api.github.com/repos/simple-icons/simple-icons/actions/workflows/create-release.yml/dispatches
# Replacing <token> by a personal access token with scope `public_repo`

jobs:
  release-pr:
    runs-on: ubuntu-latest
    outputs:
      did-create-pr: ${{ steps.release.outputs.did-create-pr }}
      new-version: ${{ steps.release.outputs.new-version }}
    steps:
      - uses: simple-icons/release-action@master
        id: release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  version-bump:
    runs-on: ubuntu-latest
    needs: release-pr
    if: needs.release-pr.outputs.did-create-pr == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Ensure we are checked out on the develop branch
          ref: develop
      - name: Bump version
        run: node ./scripts/release/bump-version.js "${{ needs.release-pr.outputs.new-version }}"
      - name: Update major version in CDN URLs
        run: node ./scripts/release/update-cdn-urls.js
      - name: Update slugs table
        run: node ./scripts/release/update-slugs-table.js
      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: version bump
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
